app/controllers/campaigns_controller.rb
=> updated method

app/controllers/campaigns_controller.rb, app/views/campaigns/show.html.erb
Quick fix for the delete (turbo_method was in the wrong place)
=> fixed delete button

app/controllers/sessions_controller.rb, app/models/session.rb, db/migrate/20250128150412_create_sessions.rb, db/schema.rb, test/controllers/sessions_controller_test.rb, test/models/session_test.rb
created sessions controller and migration
=> sessions migration and controller

app/assets/stylesheets/components/_navbar.scss, app/javascript/controllers/navbar_controller.js, app/models/character.rb, app/views/shared/_navbar.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
=> New navbar

app/controllers/campaign_characters_controller.rb, app/controllers/campaigns_controller.rb, app/controllers/pages_controller.rb, app/models/campaign.rb, app/models/campaign_character.rb, app/models/user.rb, app/policies/campaign_policy.rb, app/views/campaigns/show.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb, db/migrate/20250129203629_change_columns_in_campaign_character.rb, db/schema.rb, test/controllers/campaign_characters_controller_test.rb
This uses the campaign_character table as a join table for users and campaigns to facilitate invites
Added pending invites/joined campaigns in the dashboard
Added party information in the campaign show page
=> Campaign invites experiment

app/assets/stylesheets/components/_buttons.scss, app/views/campaigns/index.html.erb
=> added edit btn

Gemfile, Gemfile.lock, app/controllers/campaigns_controller.rb, app/controllers/messages_controller.rb, app/javascript/controllers/chat_scroll_controller.js, app/javascript/controllers/reset_form_controller.js, app/models/campaign.rb, app/models/campaign_character.rb, app/models/message.rb, app/models/user.rb, app/views/campaigns/_message.html.erb, app/views/campaigns/show.html.erb, config/cable.yml, config/routes.rb, db/migrate/20250130122428_create_solid_cable_message.solid_cable.rb, db/migrate/20250130122429_index_channels.solid_cable.rb, db/migrate/20250130123723_create_messages.rb, db/schema.rb, test/controllers/messages_controller_test.rb, test/models/message_test.rb
Chat feature for party members on the campaign show page
Currently shows to all users, will restrict that to party members only in the next update
Currently does not scroll to the bottom after each new message, will be fixed in the next update
=> Added chat feature to campaign show page

app/assets/stylesheets/components/_characters.scss, app/views/shared/_navbar.html.erb, db/migrate/20250205101454_add_portrait_to_characters.rb
=> Portraits migration added

app/assets/stylesheets/components/_campaigns.scss, app/assets/stylesheets/components/_characters.scss, app/views/pages/dashboard.html.erb, db/schema.rb
=> added plus icons to dash

app/assets/stylesheets/components/_campaigns.scss, app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_simple_calendar.scss, app/views/pages/dashboard.html.erb, app/views/simple_calendar/_week_calendar.html.erb
=> dashboard styling

app/controllers/users/registrations_controller.rb, app/javascript/application.js, app/models/user.rb, app/views/campaigns/show.html.erb, app/views/devise/registrations/edit.html.erb
by passed pw for setting availability
=> by passed pw for setting availability

app/assets/stylesheets/components/_campaign_show.scss, app/assets/stylesheets/components/_simple_calendar.scss, app/controllers/calendars_controller.rb, app/controllers/sessions_controller.rb, app/models/session.rb, app/views/calendars/index.html.erb, app/views/simple_calendar/_month_calendar.html.erb
responsive styling on calendar and campaign show page
=> responsive calendar and campaign show page

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_camp_index.scss, app/assets/stylesheets/components/_campaign_show.scss, app/views/campaigns/_form.html.erb, app/views/campaigns/show.html.erb
editing glow and font spacing in show pg
=> small styling bits

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_campaign_show.scss, app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_popup.scss, app/views/campaigns/show.html.erb, app/views/pages/dashboard.html.erb
small styling fixes on dashboard and notes modal
=> dashboard styling and notes

app/assets/stylesheets/components/_navbar.scss, app/javascript/controllers/notifications_controller.js, app/views/notifications/_badge.html.erb, app/views/shared/_navbar.html.erb, config/cable.yml
Changed the styling of the notifications badge (text colour, size and position to help with readability)
Stopped the constantly polling from Solid_Cable
Notifications now only delete when you click on them
=> small fixes

app/assets/stylesheets/components/_campaigns.scss, app/assets/stylesheets/components/_dashboard.scss
=> dashboard padding

app/controllers/application_controller.rb, app/controllers/campaigns_controller.rb, app/controllers/characters_controller.rb, app/models/campaign_character.rb, app/views/campaigns/show.html.erb, app/views/characters/show.html.erb
Fixed the back paths for campaigns and characters
Fixed dependents for character sessions, campaigns should be deleteable now
=> More fixes

app/assets/stylesheets/components/_buttons.scss, app/views/campaigns/show.html.erb
Should disable while there's a pending session now
=> create next session button now disables

app/services/session_scheduler_service.rb, app/views/devise/registrations/edit.html.erb
added dates to availability and changed notif message so it displays time and date
=> Avail dates

app/views/campaigns/show.html.erb, app/views/characters/show.html.erb
Seriously hate these things now, think I've accounted for all edge cases (he did not account for all edge cases)
=> fixed back buttons... again
